/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
	MutationFunction,
	QueryFunction,
	QueryKey,
	UseMutationOptions,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import type {
	CreateNotificationDto,
	NotificationDto,
	NotificationsControllerCreateParams,
	NotificationsControllerFindAllParams,
} from "./models";
import { mutator } from "./mutators/index";
import type { ErrorType } from "./mutators/index";

export const notificationsControllerCreate = (
	createNotificationDto: CreateNotificationDto,
	params?: NotificationsControllerCreateParams,
) => {
	return mutator<NotificationDto>({
		url: `/v1/notifications`,
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: createNotificationDto,
		params,
	});
};

export const getNotificationsControllerCreateMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof notificationsControllerCreate>>,
		TError,
		{ data: CreateNotificationDto; params?: NotificationsControllerCreateParams },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof notificationsControllerCreate>>,
	TError,
	{ data: CreateNotificationDto; params?: NotificationsControllerCreateParams },
	TContext
> => {
	const { mutation: mutationOptions } = options ?? {};

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof notificationsControllerCreate>>,
		{ data: CreateNotificationDto; params?: NotificationsControllerCreateParams }
	> = (props) => {
		const { data, params } = props ?? {};

		return notificationsControllerCreate(data, params);
	};

	return { mutationFn, ...mutationOptions };
};

export type NotificationsControllerCreateMutationResult = NonNullable<
	Awaited<ReturnType<typeof notificationsControllerCreate>>
>;
export type NotificationsControllerCreateMutationBody = CreateNotificationDto;
export type NotificationsControllerCreateMutationError = ErrorType<unknown>;

export const useNotificationsControllerCreate = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof notificationsControllerCreate>>,
		TError,
		{ data: CreateNotificationDto; params?: NotificationsControllerCreateParams },
		TContext
	>;
}) => {
	const mutationOptions = getNotificationsControllerCreateMutationOptions(options);

	return useMutation(mutationOptions);
};
export const notificationsControllerFindAll = (
	params?: NotificationsControllerFindAllParams,
	signal?: AbortSignal,
) => {
	return mutator<NotificationDto[]>({ url: `/v1/notifications`, method: "GET", params, signal });
};

export const getNotificationsControllerFindAllQueryKey = (
	params?: NotificationsControllerFindAllParams,
) => {
	return [`/v1/notifications`, ...(params ? [params] : [])] as const;
};

export const getNotificationsControllerFindAllQueryOptions = <
	TData = Awaited<ReturnType<typeof notificationsControllerFindAll>>,
	TError = ErrorType<unknown>,
>(
	params?: NotificationsControllerFindAllParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof notificationsControllerFindAll>>, TError, TData>
		>;
	},
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getNotificationsControllerFindAllQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof notificationsControllerFindAll>>> = ({
		signal,
	}) => notificationsControllerFindAll(params, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof notificationsControllerFindAll>>,
		TError,
		TData
	> & { queryKey: QueryKey };
};

export type NotificationsControllerFindAllQueryResult = NonNullable<
	Awaited<ReturnType<typeof notificationsControllerFindAll>>
>;
export type NotificationsControllerFindAllQueryError = ErrorType<unknown>;

export const useNotificationsControllerFindAll = <
	TData = Awaited<ReturnType<typeof notificationsControllerFindAll>>,
	TError = ErrorType<unknown>,
>(
	params?: NotificationsControllerFindAllParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof notificationsControllerFindAll>>, TError, TData>
		>;
	},
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
	const queryOptions = getNotificationsControllerFindAllQueryOptions(params, options);

	const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

	query.queryKey = queryOptions.queryKey;

	return query;
};
