/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */
import type { User } from "./user";

export interface CallbackRequest {
	createdAt: string;
	deletedAt: string | null;
	id: string;
	isResolved: boolean;
	updatedAt: string;
	user?: User;
	userId: string;
}
