/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */
import type { SuccessResponseDto } from "./successResponseDto";
import type { CallbackRequestControllerUpdate200AllOf } from "./callbackRequestControllerUpdate200AllOf";

export type CallbackRequestControllerUpdate200 = SuccessResponseDto &
	CallbackRequestControllerUpdate200AllOf;
