/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */

export interface CallbackRequestDto {
	createdAt: string;
	deletedAt: string | null;
	id: string;
	isResolved: boolean;
	updatedAt: string;
	userId: string;
}
