/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */
import type { SuccessResponseDto } from "./successResponseDto";
import type { CallbackRequestControllerCreate201AllOf } from "./callbackRequestControllerCreate201AllOf";

export type CallbackRequestControllerCreate201 = SuccessResponseDto &
	CallbackRequestControllerCreate201AllOf;
