/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */
import type { SuccessResponseDto } from "./successResponseDto";
import type { ContactRequestControllerCreate201AllOf } from "./contactRequestControllerCreate201AllOf";

export type ContactRequestControllerCreate201 = SuccessResponseDto &
	ContactRequestControllerCreate201AllOf;
