/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */
import type { ContactRequestDto } from "./contactRequestDto";

export type ContactRequestControllerUpdate200AllOf = {
	result?: ContactRequestDto;
};
