/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */

export interface ContactRequestDto {
	createdAt: string;
	deletedAt: string | null;
	email: string;
	firstName: string;
	id: string;
	isResolved: boolean;
	lastName: string;
	message: string;
	phoneNumber: string | null;
	updatedAt: string;
}
