/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */
import type { SuccessResponseDto } from "./successResponseDto";
import type { ContactRequestControllerUpdate200AllOf } from "./contactRequestControllerUpdate200AllOf";

export type ContactRequestControllerUpdate200 = SuccessResponseDto &
	ContactRequestControllerUpdate200AllOf;
