/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */
import type { CreateNotificationDtoData } from "./createNotificationDtoData";

export interface CreateNotificationDto {
	body: string;
	data?: CreateNotificationDtoData;
	title: string;
	userId: string;
}
