/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */
import type { CreateMedicationDtoFrequency } from "./createMedicationDtoFrequency";
import type { CreateMedicationDtoSpecificDays } from "./createMedicationDtoSpecificDays";

export interface CreateMedicationDto {
	frequency: CreateMedicationDtoFrequency;
	intervalCount?: number | null;
	intervalUnit?: string | null;
	name: string;
	specificDays: CreateMedicationDtoSpecificDays;
	startDate: string;
}
