/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */

export type CreateRedeemDtoMethod =
	(typeof CreateRedeemDtoMethod)[keyof typeof CreateRedeemDtoMethod];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateRedeemDtoMethod = {
	GIFTCARD: "GIFTCARD",
} as const;
