/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */

export type CreateRedeemDtoGiftCardType =
	| (typeof CreateRedeemDtoGiftCardType)[keyof typeof CreateRedeemDtoGiftCardType]
	| null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateRedeemDtoGiftCardType = {
	AMAZON: "AMAZON",
	WALMART: "WALMART",
	TARGET: "TARGET",
	OTHER: "OTHER",
} as const;
