/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */

export type CreatePushTokenDtoPlatform =
	(typeof CreatePushTokenDtoPlatform)[keyof typeof CreatePushTokenDtoPlatform];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreatePushTokenDtoPlatform = {
	IOS: "IOS",
	ANDROID: "ANDROID",
} as const;
