/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */

export type CreateMedicationDtoSpecificDays =
	(typeof CreateMedicationDtoSpecificDays)[keyof typeof CreateMedicationDtoSpecificDays];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateMedicationDtoSpecificDays = {
	SUNDAY: "SUNDAY",
	MONDAY: "MONDAY",
	TUESDAY: "TUESDAY",
	WEDNESDAY: "WEDNESDAY",
	THURSDAY: "THURSDAY",
	FRIDAY: "FRIDAY",
	SATURDAY: "SATURDAY",
} as const;
