/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */
import type { CreateMedicationDtoFrequency } from "./createMedicationDtoFrequency";
import type { CreateMedicationDtoIntervalUnit } from "./createMedicationDtoIntervalUnit";
import type { CreateMedicationDtoSpecificDaysItem } from "./createMedicationDtoSpecificDaysItem";

export interface CreateMedicationDto {
	dosage?: string | null;
	frequency: CreateMedicationDtoFrequency;
	intervalCount?: number | null;
	intervalUnit?: CreateMedicationDtoIntervalUnit;
	name: string;
	noOfPills: number;
	specificDays?: CreateMedicationDtoSpecificDaysItem[];
	startDate: string;
}
