/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */
import type { CreatePushTokenDtoPlatform } from "./createPushTokenDtoPlatform";

export interface CreatePushTokenDto {
	apnToken?: string | null;
	device: string;
	identifier: string;
	platform: CreatePushTokenDtoPlatform;
	token: string;
	userId: string;
}
