/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */
import type { CompletedInrTest } from "./completedInrTest";
import type { TakenMedicationDto } from "./takenMedicationDto";

export interface DashboardDataDto {
	incentiveAmount: number;
	inrTests: CompletedInrTest[];
	takenMedications: TakenMedicationDto[];
	wellnessScore: number | null;
}
