/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */
import type { SuccessResponseDto } from "./successResponseDto";
import type { GiftCardTypeControllerUpdate200AllOf } from "./giftCardTypeControllerUpdate200AllOf";

export type GiftCardTypeControllerUpdate200 = SuccessResponseDto &
	GiftCardTypeControllerUpdate200AllOf;
