/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */
import type { SuccessResponseDto } from "./successResponseDto";
import type { GiftCardTypeControllerCreate201AllOf } from "./giftCardTypeControllerCreate201AllOf";

export type GiftCardTypeControllerCreate201 = SuccessResponseDto &
	GiftCardTypeControllerCreate201AllOf;
