/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */
import type { Redeem } from "./redeem";

export interface GiftCardType {
	createdAt: string;
	deletedAt: string | null;
	id: string;
	name: string;
	redeems?: Redeem[];
	updatedAt: string;
}
