/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */
import type { SuccessResponseDto } from "./successResponseDto";
import type { IncentivesControllerCreate201AllOf } from "./incentivesControllerCreate201AllOf";

export type IncentivesControllerCreate201 = SuccessResponseDto & IncentivesControllerCreate201AllOf;
