/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */
import type { SuccessResponseDto } from "./successResponseDto";
import type { IncentivesControllerUpdate200AllOf } from "./incentivesControllerUpdate200AllOf";

export type IncentivesControllerUpdate200 = SuccessResponseDto & IncentivesControllerUpdate200AllOf;
