/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */

export interface InrTestDto {
	createdAt: string;
	date: string;
	deletedAt: string | null;
	id: string;
	inrValue: number;
	remarks: string | null;
	updatedAt: string;
	verificationImage: string | null;
}
