/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */
import type { InrTestDto } from "./inrTestDto";

export type InrTestControllerUpdate200AllOf = {
	result?: InrTestDto;
};
