/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */
import type { SuccessResponseDto } from "./successResponseDto";
import type { InrTestControllerCreate201AllOf } from "./inrTestControllerCreate201AllOf";

export type InrTestControllerCreate201 = SuccessResponseDto & InrTestControllerCreate201AllOf;
