/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */
import type { SuccessResponseDto } from "./successResponseDto";
import type { InrTestControllerUpdate200AllOf } from "./inrTestControllerUpdate200AllOf";

export type InrTestControllerUpdate200 = SuccessResponseDto & InrTestControllerUpdate200AllOf;
