/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */
import type { MedicationDtoFrequency } from "./medicationDtoFrequency";
import type { MedicationDtoIntervalUnit } from "./medicationDtoIntervalUnit";
import type { MedicationDtoSpecificDaysItem } from "./medicationDtoSpecificDaysItem";

export interface MedicationDto {
	createdAt: string;
	deletedAt: string | null;
	dosage: string | null;
	frequency: MedicationDtoFrequency;
	id: string;
	intervalCount: number | null;
	intervalUnit: MedicationDtoIntervalUnit;
	name: string;
	noOfPills: number;
	specificDays: MedicationDtoSpecificDaysItem[];
	startDate: string;
	updatedAt: string;
}
