/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */

export type MedicationDtoSpecificDaysItem =
	(typeof MedicationDtoSpecificDaysItem)[keyof typeof MedicationDtoSpecificDaysItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MedicationDtoSpecificDaysItem = {
	SUNDAY: "SUNDAY",
	MONDAY: "MONDAY",
	TUESDAY: "TUESDAY",
	WEDNESDAY: "WEDNESDAY",
	THURSDAY: "THURSDAY",
	FRIDAY: "FRIDAY",
	SATURDAY: "SATURDAY",
} as const;
