/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */
import type { MedicationDtoFrequency } from "./medicationDtoFrequency";
import type { MedicationDtoSpecificDays } from "./medicationDtoSpecificDays";

export interface MedicationDto {
	createdAt: string;
	deletedAt: string | null;
	frequency: MedicationDtoFrequency;
	id: string;
	intervalCount: number | null;
	intervalUnit: string | null;
	name: string;
	specificDays: MedicationDtoSpecificDays;
	startDate: string;
	updatedAt: string;
}
