/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */

export type MedicationFrequency = (typeof MedicationFrequency)[keyof typeof MedicationFrequency];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MedicationFrequency = {
	DAILY: "DAILY",
	SPECIFIC_DAYS: "SPECIFIC_DAYS",
	DAYS_INTERVAL: "DAYS_INTERVAL",
	AS_NEEDED: "AS_NEEDED",
} as const;
