/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */

export type MedicationDtoIntervalUnit =
	| (typeof MedicationDtoIntervalUnit)[keyof typeof MedicationDtoIntervalUnit]
	| null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MedicationDtoIntervalUnit = {
	DAY: "DAY",
	WEEK: "WEEK",
	MONTH: "MONTH",
} as const;
