/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */
import type { SuccessResponseDto } from "./successResponseDto";
import type { MedicationsControllerCreate201AllOf } from "./medicationsControllerCreate201AllOf";

export type MedicationsControllerCreate201 = SuccessResponseDto &
	MedicationsControllerCreate201AllOf;
