/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */
import type { SuccessResponseDto } from "./successResponseDto";
import type { MedicationsControllerUpdate200AllOf } from "./medicationsControllerUpdate200AllOf";

export type MedicationsControllerUpdate200 = SuccessResponseDto &
	MedicationsControllerUpdate200AllOf;
