/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */

export type MedicationDtoFrequency =
	(typeof MedicationDtoFrequency)[keyof typeof MedicationDtoFrequency];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MedicationDtoFrequency = {
	DAILY: "DAILY",
	SPECIFIC_DAYS: "SPECIFIC_DAYS",
	DAYS_INTERVAL: "DAYS_INTERVAL",
	AS_NEEDED: "AS_NEEDED",
} as const;
