/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */

export type MedicationIntervalUnit =
	| (typeof MedicationIntervalUnit)[keyof typeof MedicationIntervalUnit]
	| null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MedicationIntervalUnit = {
	DAY: "DAY",
	WEEK: "WEEK",
	MONTH: "MONTH",
} as const;
