/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */
import type { NotificationDtoData } from "./notificationDtoData";

export interface NotificationDto {
	body: string;
	createdAt: string;
	data: NotificationDtoData;
	deletedAt: string | null;
	id: string;
	title: string;
	updatedAt: string;
	userId: string;
}
