/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */
import type { NotificationData } from "./notificationData";
import type { User } from "./user";

export interface Notification {
	body: string;
	createdAt: string;
	data: NotificationData;
	deletedAt: string | null;
	id: string;
	title: string;
	updatedAt: string;
	user?: User;
	userId: string;
}
