/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */
import type { PushTokenPlatform } from "./pushTokenPlatform";
import type { User } from "./user";

export interface PushToken {
	apnToken: string | null;
	createdAt: string;
	deletedAt: string | null;
	device: string;
	id: string;
	identifier: string;
	platform: PushTokenPlatform;
	token: string;
	updatedAt: string;
	user?: User;
	userId: string;
}
