/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */
import type { PushTokenDtoPlatform } from "./pushTokenDtoPlatform";

export interface PushTokenDto {
	apnToken: string | null;
	createdAt: string;
	deletedAt: string | null;
	device: string;
	id: string;
	identifier: string;
	platform: PushTokenDtoPlatform;
	token: string;
	updatedAt: string;
	userId: string;
}
