/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */

export type PushTokenDtoPlatform = (typeof PushTokenDtoPlatform)[keyof typeof PushTokenDtoPlatform];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PushTokenDtoPlatform = {
	IOS: "IOS",
	ANDROID: "ANDROID",
} as const;
