/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */
import type { SuccessResponseDto } from "./successResponseDto";
import type { RedeemsControllerUpdate200AllOf } from "./redeemsControllerUpdate200AllOf";

export type RedeemsControllerUpdate200 = SuccessResponseDto & RedeemsControllerUpdate200AllOf;
