/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */

export type RedeemDtoMethod = (typeof RedeemDtoMethod)[keyof typeof RedeemDtoMethod];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RedeemDtoMethod = {
	GIFTCARD: "GIFTCARD",
} as const;
