/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */
import type { SuccessResponseDto } from "./successResponseDto";
import type { RedeemsControllerCreate201AllOf } from "./redeemsControllerCreate201AllOf";

export type RedeemsControllerCreate201 = SuccessResponseDto & RedeemsControllerCreate201AllOf;
