/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */
import type { RedeemGiftCardType } from "./redeemGiftCardType";
import type { RedeemMethod } from "./redeemMethod";
import type { User } from "./user";

export interface Redeem {
	amount: number;
	createdAt: string;
	deletedAt: string | null;
	expiryAt: string | null;
	giftCardCode: string | null;
	giftCardType?: RedeemGiftCardType;
	giftCardTypeId: string | null;
	id: string;
	method: RedeemMethod;
	processedAt: string | null;
	updatedAt: string;
	user?: User;
	userId: string;
}
