/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */

export type RedeemDtoGiftCardType =
	| (typeof RedeemDtoGiftCardType)[keyof typeof RedeemDtoGiftCardType]
	| null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RedeemDtoGiftCardType = {
	AMAZON: "AMAZON",
	WALMART: "WALMART",
	TARGET: "TARGET",
	OTHER: "OTHER",
} as const;
