/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */
import type { SuccessResponseDto } from "./successResponseDto";
import type { RemindersControllerCreate201AllOf } from "./remindersControllerCreate201AllOf";

export type RemindersControllerCreate201 = SuccessResponseDto & RemindersControllerCreate201AllOf;
