/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */
import type { ReminderDto } from "./reminderDto";

export type RemindersControllerCreate201AllOf = {
	result?: ReminderDto;
};
