/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */
import type { SuccessResponseDto } from "./successResponseDto";
import type { RemindersControllerUpdate200AllOf } from "./remindersControllerUpdate200AllOf";

export type RemindersControllerUpdate200 = SuccessResponseDto & RemindersControllerUpdate200AllOf;
