/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */

export interface ReminderDto {
	acknowledgedAt: string | null;
	createdAt: string;
	deletedAt: string | null;
	description: string | null;
	id: string;
	medicationId: string;
	remindAt: string;
	status: boolean | null;
	title: string;
	updatedAt: string;
}
