/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */

export interface UpdateWellnessScoreDto {
	date?: string;
	remarks?: string | null;
	score?: number;
	userId?: string;
}
