/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */

export interface UpdateReminderDto {
	acknowledgedAt?: string | null;
	description?: string | null;
	medicationId?: string;
	remindAt?: string;
	status?: boolean | null;
	title?: string;
}
