/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */

export type UpdateRedeemDtoMethod =
	(typeof UpdateRedeemDtoMethod)[keyof typeof UpdateRedeemDtoMethod];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateRedeemDtoMethod = {
	GIFTCARD: "GIFTCARD",
} as const;
