/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */
import type { UpdateMedicationDtoFrequency } from "./updateMedicationDtoFrequency";
import type { UpdateMedicationDtoSpecificDays } from "./updateMedicationDtoSpecificDays";

export interface UpdateMedicationDto {
	frequency?: UpdateMedicationDtoFrequency;
	intervalCount?: number | null;
	intervalUnit?: string | null;
	name?: string;
	specificDays?: UpdateMedicationDtoSpecificDays;
	startDate?: string;
}
