/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */
import type { UpdateRedeemDtoGiftCardType } from "./updateRedeemDtoGiftCardType";
import type { UpdateRedeemDtoMethod } from "./updateRedeemDtoMethod";

export interface UpdateRedeemDto {
	amount?: number;
	giftCardCode?: string | null;
	giftCardType?: UpdateRedeemDtoGiftCardType;
	method?: UpdateRedeemDtoMethod;
	processedAt?: string | null;
	userId?: string;
}
