/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */
import type { UpdateMedicationDtoFrequency } from "./updateMedicationDtoFrequency";
import type { UpdateMedicationDtoIntervalUnit } from "./updateMedicationDtoIntervalUnit";
import type { UpdateMedicationDtoSpecificDaysItem } from "./updateMedicationDtoSpecificDaysItem";

export interface UpdateMedicationDto {
	dosage?: string | null;
	frequency?: UpdateMedicationDtoFrequency;
	intervalCount?: number | null;
	intervalUnit?: UpdateMedicationDtoIntervalUnit;
	name?: string;
	noOfPills?: number;
	specificDays?: UpdateMedicationDtoSpecificDaysItem[];
	startDate?: string;
	time?: string;
}
