/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */

export interface UpdateInrTestDto {
	date?: string;
	inrValue?: number;
	remarks?: string | null;
	verificationImage?: string | null;
}
