/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */

export interface UpdateUserDto {
	email?: string;
	fullName?: string;
	phoneNumber?: string | null;
	stickyReminder?: boolean;
}
