/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */

export interface UpdateContactRequestDto {
	email?: string;
	firstName?: string;
	isResolved?: boolean;
	lastName?: string;
	message?: string | null;
	phoneNumber?: string | null;
}
