/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */

export interface UploadFileRequestDto {
	file: Blob;
	/** The name to use for the uploaded file (defaults to the original filename) */
	fileName?: string;
	/** The path to upload the file to */
	path: string;
}
