/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */
import type { UserDtoRole } from "./userDtoRole";

export interface UserDto {
	createdAt: string;
	deletedAt: string | null;
	email: string;
	fullName: string;
	id: string;
	isVerified: boolean;
	phoneNumber: string | null;
	role: UserDtoRole;
	stickyReminder: boolean;
	updatedAt: string;
}
