/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */
import type { SuccessResponseDto } from "./successResponseDto";
import type { UsersControllerUpdate200AllOf } from "./usersControllerUpdate200AllOf";

export type UsersControllerUpdate200 = SuccessResponseDto & UsersControllerUpdate200AllOf;
