/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */
import type { SuccessResponseDto } from "./successResponseDto";
import type { UsersControllerCreate201AllOf } from "./usersControllerCreate201AllOf";

export type UsersControllerCreate201 = SuccessResponseDto & UsersControllerCreate201AllOf;
