/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */
import type { UserRole } from "./userRole";

export interface User {
	createdAt: string;
	deletedAt: string | null;
	email: string;
	fullName: string;
	id: string;
	isVerified: boolean;
	phoneNumber: string | null;
	role: UserRole;
	stickyReminder: boolean;
	updatedAt: string;
}
