/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */
import type { CallbackRequest } from "./callbackRequest";
import type { Notification } from "./notification";
import type { PushToken } from "./pushToken";
import type { UserRole } from "./userRole";

export interface User {
	callbackRequests?: CallbackRequest[];
	createdAt: string;
	deletedAt: string | null;
	email: string;
	fullName: string;
	id: string;
	isVerified: boolean;
	notifications?: Notification[];
	phoneNumber: string | null;
	pushTokens?: PushToken[];
	role: UserRole;
	stickyReminder: boolean;
	updatedAt: string;
}
