/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */
import type { UserDto } from "./userDto";

export type UsersControllerUpdate200AllOf = {
	result?: UserDto;
};
