/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */

export interface WellnessScoreDto {
	createdAt: string;
	date: string;
	deletedAt: string | null;
	id: string;
	remarks: string | null;
	score: number;
	updatedAt: string;
	userId: string;
}
