/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */
import type { SuccessResponseDto } from "./successResponseDto";
import type { WellnessScoresControllerUpdate200AllOf } from "./wellnessScoresControllerUpdate200AllOf";

export type WellnessScoresControllerUpdate200 = SuccessResponseDto &
	WellnessScoresControllerUpdate200AllOf;
