/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * RemInr Api
 * OpenAPI spec version: 1.0
 */
import type { SuccessResponseDto } from "./successResponseDto";
import type { WellnessScoresControllerCreate201AllOf } from "./wellnessScoresControllerCreate201AllOf";

export type WellnessScoresControllerCreate201 = SuccessResponseDto &
	WellnessScoresControllerCreate201AllOf;
