name: Push to app store

on:
  workflow_dispatch:

env:
  IOS_BUILD_PATH: "ios/build/outputs/ipa/release/RemInr.ipa"

jobs:
  push-ios:
    name: Build and Deploy iOS
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"
      - name: Get build number
        id: get-build
        uses: mlilback/build-number@v1
        with:
          base: -2 # This will be added to the current build number
          run-id: ${{ github.run_number }}
      - name: Creating .env file
        run: |
          echo "${{ vars.PROD_ENV }}" > .env
          echo "RN_VERSION_CODE=${{ steps.get-build.outputs.build-number }}" >> .env
          echo "RN_VERSION_NAME=${{ vars.PROD_BUILD_NAME }}" >> .env
      - name: Create Google Info.plist
        run: |
          echo "${{ secrets.PROD_GOOGLE_INFO_PLIST }}" | base64 --decode > ios/GoogleService-Info.plist
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Install Pods
        run: |
          npx pod-install
      - name: Build IPA
        run: |
          xcodebuild -workspace ios/RemInr.xcworkspace \
            -scheme RemInr \
            -configuration Release \
            -archivePath ios/build/archive/RemInr.xcarchive \
            -destination 'generic/platform=iOS' \
            clean archive | xcpretty
      - name: Export Archive
        run: |
          xcodebuild -exportArchive \
            -archivePath ios/build/archive/RemInr.xcarchive \
            -exportOptionsPlist ios/ExportOptions-AppStore.plist \
            -exportPath ios/build/outputs/ipa/release | xcpretty
      - name: Validate IPA
        run: |
          xcrun altool --validate-app \
            --type ios \
            -f ${{ env.IOS_BUILD_PATH }} \
            --apiKey ${{ secrets.APPSTORE_CONNECT_KEY_ID }} \
            --apiIssuer ${{ secrets.APPSTORE_CONNECT_ISSUER_ID }}
      - name: Upload IPA
        run: |
          xcrun altool --upload-app \
            --type ios \
            -f ${{ env.IOS_BUILD_PATH }} \
            --apiKey ${{ secrets.APPSTORE_CONNECT_KEY_ID }} \
            --apiIssuer ${{ secrets.APPSTORE_CONNECT_ISSUER_ID }}
      - name: Post Distribute
        run: |
          git clean -ffdx
